### ISSUE TITLE
{error: "Signature verification failed"} 

### ISSUE THREAD

**Issue by ciumexan** [amaurymartiny/login-with-metamask-demo#3] opened 2018-06-16 20:17 UTC
Hello, 
From time to time i get this after login (if i login/logout for a few times) :

`{error: "Signature verification failed"}`

on the back-end i get this error in the console: 
<img width="838" alt="screen shot 2018-06-16 at 21 13 19" src="https://user-images.githubusercontent.com/3225668/41502088-392b2142-71aa-11e8-9fa3-6edcc75a18b0.png">

Then, on the frontend i see:

![screen shot 2018-06-16 at 21 11 24](https://user-images.githubusercontent.com/3225668/41502090-49e308e2-71aa-11e8-86e7-227c4fd59e04.png)

Here is my console on the frontend:

![screen shot 2018-06-16 at 21 11 45](https://user-images.githubusercontent.com/3225668/41502093-583b6b8c-71aa-11e8-8396-6ae96285f5db.png)

![screen shot 2018-06-16 at 21 11 59](https://user-images.githubusercontent.com/3225668/41502095-5ef88ca2-71aa-11e8-9297-416b3feeb780.png)

It has something to do with jwt token?

Can you tell mehow can i investigate where is the pb? 

If i delete cookies on the app itself, I can login, but immediately throws that error... 

I cannot figure why.

**Comment by amaurymartiny** [comment] 2018-06-17 11:45
Unfortunately I cannot reproduce, I just tried logging in and out 20 times, no errors.

Could you add the following lines at this place: https://github.com/amaurymartiny/login-with-metamask-demo/blob/master/backend/src/services/auth/controller.js#L48?

```javascript
console.log('user', user);
console.log('msg', msg);
console.log('msgBuffer', msgBuffer.toString('hex'));
console.log('msgHash', msgHash.toString('hex'));
console.log('signatureBuffer', signatureBuffer.toString('hex'));
console.log('v', signatureParams.v);
console.log('s', signatureParams.s.toString('hex'));
console.log('r', signatureParams.r.toString('hex'));
console.log('publicKey', publicKey.toString('hex'));
console.log('addressBuffer', addressBuffer.toString('hex'));
console.log('address', address);
console.log('publicAddress', publicAddress);
```

and paste the logs in the backend. It will help me debug what went wrong with the signature verification.

**Comment by ciumexan** [comment] 2018-06-18 16:49
This is my backend output 👍 
https://pastebin.com/JEphQ90X

**Comment by ciumexan** [comment] 2018-06-21 18:41
hello back
did you had any chance on looking at it? 
I am still struggling with it, as i will need to use this with nextjs. 
thanks

**Comment by amaurymartiny** [comment] 2018-06-21 21:18
The backend logs look good.

Could you add one line in the backend code:
```javascript
        console.log('user', user);
        console.log('msg', msg);
        console.log('signature', signature);
        console.log('msgBuffer', msgBuffer.toString('hex'));
        console.log('msgHash', msgHash.toString('hex'));
        console.log('signatureBuffer', signatureBuffer.toString('hex'));
        console.log('v', signatureParams.v);
        console.log('s', signatureParams.s.toString('hex'));
        console.log('r', signatureParams.r.toString('hex'));
        console.log('publicKey', publicKey.toString('hex'));
        console.log('addressBuffer', addressBuffer.toString('hex'));
        console.log('address', address);
        console.log('publicAddress', publicAddress);
```

And also, in the frontend, add this console.log at this line: https://github.com/amaurymartiny/login-with-metamask-demo/blob/master/frontend/src/Login/Login.js#L70-L71
```javascript
          if (err) return reject(err);
          console.log(publicAddress, nonce, signature);
          return resolve({ publicAddress, signature });
```

**Comment by ciumexan** [comment] 2018-06-25 17:34
got it. will do asap.

**Comment by amaurymartiny** [comment] 2018-06-27 17:49
Interesting. This may take some time to debug though, so let's both be patient :)

1. When do the above error fire? On startup? When you click on the login button?
2. Did you add the `console.log(publicAddress, nonce, signature);` on the frontend, as I described above? Does that log in the console?

Thanks.

**Comment by amaurymartiny** [comment] 2019-04-19 15:34
I'll close this. Please re-open if it's still reproducible.

**Closed by amaurymartiny** 2019-04-19 15:34 UTC
